apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world-deploy-prod
spec:
  replicas: 2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hello-world-app-prod
    spec:
      containers:
      - name: hello-world-pod
        image: 467269547207.dkr.ecr.us-west-2.amazonaws.com/hello-world:VERSION
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 5
          failureThreshold: 2
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 2
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 0.8
            memory: 2048Mi
          requests:
            cpu: 0.8
            memory: 500Mi
