apiVersion: v1
kind: Service
metadata:
  name: hello-world-lb-qal
  labels:
    app: hello-world-app-qal
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    nodePort: 30002
    protocol: TCP
  selector:
    app: hello-world-app-qal
