apiVersion: v1
kind: Service
metadata:
  name: hello-world-lb
  labels:
    app: hello-world-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: hello-world-app
