apiVersion: v1
kind: Service
metadata:
  name: hello-world-lb-prod
  labels:
    app: hello-world-app-prod
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    nodePort: 30003
    protocol: TCP
  selector:
    app: hello-world-app-prod
